// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/uuid-service/v1/resources/uuid.resource.v1.proto

package resourcev1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on NextIDReq with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NextIDReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NextIDReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NextIDReqMultiError, or nil
// if none found.
func (m *NextIDReq) ValidateAll() error {
	return m.validate(true)
}

func (m *NextIDReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return NextIDReqMultiError(errors)
	}

	return nil
}

// NextIDReqMultiError is an error wrapping multiple validation errors returned
// by NextIDReq.ValidateAll() if the designated constraints aren't met.
type NextIDReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NextIDReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NextIDReqMultiError) AllErrors() []error { return m }

// NextIDReqValidationError is the validation error returned by
// NextIDReq.Validate if the designated constraints aren't met.
type NextIDReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NextIDReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NextIDReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NextIDReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NextIDReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NextIDReqValidationError) ErrorName() string { return "NextIDReqValidationError" }

// Error satisfies the builtin error interface
func (e NextIDReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNextIDReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NextIDReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NextIDReqValidationError{}

// Validate checks the field values on NextIDResp with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NextIDResp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NextIDResp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NextIDRespMultiError, or
// nil if none found.
func (m *NextIDResp) ValidateAll() error {
	return m.validate(true)
}

func (m *NextIDResp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Code

	// no validation rules for Reason

	// no validation rules for Message

	// no validation rules for Metadata

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NextIDRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NextIDRespValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NextIDRespValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return NextIDRespMultiError(errors)
	}

	return nil
}

// NextIDRespMultiError is an error wrapping multiple validation errors
// returned by NextIDResp.ValidateAll() if the designated constraints aren't met.
type NextIDRespMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NextIDRespMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NextIDRespMultiError) AllErrors() []error { return m }

// NextIDRespValidationError is the validation error returned by
// NextIDResp.Validate if the designated constraints aren't met.
type NextIDRespValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NextIDRespValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NextIDRespValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NextIDRespValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NextIDRespValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NextIDRespValidationError) ErrorName() string { return "NextIDRespValidationError" }

// Error satisfies the builtin error interface
func (e NextIDRespValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNextIDResp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NextIDRespValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NextIDRespValidationError{}

// Validate checks the field values on NextIDRespData with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NextIDRespData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NextIDRespData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NextIDRespDataMultiError,
// or nil if none found.
func (m *NextIDRespData) ValidateAll() error {
	return m.validate(true)
}

func (m *NextIDRespData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return NextIDRespDataMultiError(errors)
	}

	return nil
}

// NextIDRespDataMultiError is an error wrapping multiple validation errors
// returned by NextIDRespData.ValidateAll() if the designated constraints
// aren't met.
type NextIDRespDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NextIDRespDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NextIDRespDataMultiError) AllErrors() []error { return m }

// NextIDRespDataValidationError is the validation error returned by
// NextIDRespData.Validate if the designated constraints aren't met.
type NextIDRespDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NextIDRespDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NextIDRespDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NextIDRespDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NextIDRespDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NextIDRespDataValidationError) ErrorName() string { return "NextIDRespDataValidationError" }

// Error satisfies the builtin error interface
func (e NextIDRespDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNextIDRespData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NextIDRespDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NextIDRespDataValidationError{}
